Update solution.md
MicrosoftDocs/power-platform pull request #2684
Opened 2024-09-24 09:43 UTC by ericregnier

Updated correct behavior on pac solution import with specifying when SolutionPackageType is Both

2024-09-24 16:21 UTC, JimDaly requested changes
See my other comments.

@petrochuk & @laneswenka 
You may want to just add this to the /help content for the import solution command.

2024-09-24 16:21 UTC, JimDaly commented on power-platform/developer/cli/reference/solution.md
> +Path to solution zip file. If not specified, assumes the current folder is a cdsproj project. If `SolutionPackageType` in cdsproj file is set to `Both`, the managed solution is used by default.
This can't be edited manually. It will be overwritten next time docs are generated.

2024-09-25 06:12 UTC, ericregnier commented
> Updated correct behavior on pac solution import with specifying when SolutionPackageType is Both

@JimDaly thanks and noted. I submitted another PR remark file instead. Cheers!

2024-09-25 17:08 UTC, JimDaly commented
Closing this in favor of #2685

2024-09-25 17:08 UTC, closed without merging